dep updates
Signed-off-by: Zoey <zoey@z0ey.de>

diff --git a/.github/workflows/lint-and-format.yml b/.github/workflows/lint-and-format.yml
--- a/.github/workflows/lint-and-format.yml
+++ b/.github/workflows/lint-and-format.yml
@@ -16,24 +16,18 @@ jobs:
       - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
         with:
           version: latest
-      - name: sponge
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y moreutils
       - name: backend
         run: |
           set -x
           cd backend
           pnpm install --frozen-lockfile
-          pnpm biome lint --write
-          pnpm biome format --write
+          pnpm biome check --write --reporter=default --reporter=github || echo "BIOME_FAILED=1" >> "$GITHUB_ENV"
       - name: frontend
         run: |
           set -x
           cd frontend
           pnpm install --frozen-lockfile
-          pnpm biome lint --write
-          pnpm biome format --write
+          pnpm biome check --write --reporter=default --reporter=github || echo "BIOME_FAILED=1" >> "$GITHUB_ENV"
           ./src/locale/scripts/locale-sort.sh
           pnpm formatjs compile-folder src/locale/src src/locale/lang
           pnpm tsc --noEmit
@@ -51,3 +45,6 @@ jobs:
           branch: lint-and-format
           title: lint-and-format
           body: lint-and-format
+      - name: biome findings
+        if: ${{ env.BIOME_FAILED == '1' }}
+        run: exit 1
